# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('title_eng', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('description_eng', models.CharField(blank=True, max_length=500)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=10000)),
                ('text_eng', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lang', models.CharField(choices=[('t', '瀪'), ('s', '简'), ('e', 'Eng')], max_length=3)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_eng', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post', to='post.Tag'),
        ),
    ]
